import "./About.css";

function About(): JSX.Element {
    return (
        <div className="About">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dapibus hendrerit turpis, eu ultricies augue maximus in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris neque nunc, tincidunt et viverra id, vehicula quis metus. Vivamus bibendum mauris nec enim malesuada, eget consequat justo sodales. Vivamus placerat eros in justo molestie tincidunt. Praesent sem sapien, tristique in aliquet at, ullamcorper eget nibh. Fusce in odio nulla. Phasellus sed nibh sapien. Suspendisse potenti. Nullam iaculis euismod ex mollis suscipit. Suspendisse ac elit accumsan, scelerisque mauris ut, pellentesque erat. Mauris nec velit vel dui tincidunt ultricies. Cras volutpat odio at velit rhoncus ornare. Vestibulum porta suscipit odio, et viverra ante. Nulla lacus ante, varius ut nisi malesuada, porta viverra nisl.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dapibus hendrerit turpis, eu ultricies augue maximus in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris neque nunc, tincidunt et viverra id, vehicula quis metus. Vivamus bibendum mauris nec enim malesuada, eget consequat justo sodales. Vivamus placerat eros in justo molestie tincidunt. Praesent sem sapien, tristique in aliquet at, ullamcorper eget nibh. Fusce in odio nulla. Phasellus sed nibh sapien. Suspendisse potenti. Nullam iaculis euismod ex mollis suscipit. Suspendisse ac elit accumsan, scelerisque mauris ut, pellentesque erat. Mauris nec velit vel dui tincidunt ultricies. Cras volutpat odio at velit rhoncus ornare. Vestibulum porta suscipit odio, et viverra ante. Nulla lacus ante, varius ut nisi malesuada, porta viverra nisl.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dapibus hendrerit turpis, eu ultricies augue maximus in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris neque nunc, tincidunt et viverra id, vehicula quis metus. Vivamus bibendum mauris nec enim malesuada, eget consequat justo sodales. Vivamus placerat eros in justo molestie tincidunt. Praesent sem sapien, tristique in aliquet at, ullamcorper eget nibh. Fusce in odio nulla. Phasellus sed nibh sapien. Suspendisse potenti. Nullam iaculis euismod ex mollis suscipit. Suspendisse ac elit accumsan, scelerisque mauris ut, pellentesque erat. Mauris nec velit vel dui tincidunt ultricies. Cras volutpat odio at velit rhoncus ornare. Vestibulum porta suscipit odio, et viverra ante. Nulla lacus ante, varius ut nisi malesuada, porta viverra nisl.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dapibus hendrerit turpis, eu ultricies augue maximus in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris neque nunc, tincidunt et viverra id, vehicula quis metus. Vivamus bibendum mauris nec enim malesuada, eget consequat justo sodales. Vivamus placerat eros in justo molestie tincidunt. Praesent sem sapien, tristique in aliquet at, ullamcorper eget nibh. Fusce in odio nulla. Phasellus sed nibh sapien. Suspendisse potenti. Nullam iaculis euismod ex mollis suscipit. Suspendisse ac elit accumsan, scelerisque mauris ut, pellentesque erat. Mauris nec velit vel dui tincidunt ultricies. Cras volutpat odio at velit rhoncus ornare. Vestibulum porta suscipit odio, et viverra ante. Nulla lacus ante, varius ut nisi malesuada, porta viverra nisl.</p>
        </div>
    );
}

export default About;
